apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-orders-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-orders-app
  template:
    metadata:
      labels:
        app: springboot-orders-app
    spec:
      containers:
      - name: orders-app
        image: gcr.io/gcp-ai-458413/springboot-orders-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-Dlogging.level.root=INFO"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "300m"
        # Log to stdout/stderr for GKE log streaming
        volumeMounts:
        - name: logs
          mountPath: /logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-orders-service
spec:
  type: LoadBalancer
  selector:
    app: springboot-orders-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
